"""Initial schema

Revision ID: ec6dbe6ac659
Revises: None
Create Date: 2026-08-24 12:59:58.722035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6dbe6ac659'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('defense_type', sa.String(length=100), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=False),
    sa.Column('epsilon', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('detection_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('anomaly_analysis_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('clean_prediction', sa.Integer(), nullable=False),
    sa.Column('clean_confidence', sa.Float(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_fgsm_attacked', sa.Boolean(), nullable=False),
    sa.Column('attack_type', sa.String(length=20), nullable=True),
    sa.Column('attack_epsilon', sa.Float(), nullable=True),
    sa.Column('adversarial_prediction', sa.Integer(), nullable=True),
    sa.Column('purified_prediction', sa.Integer(), nullable=True),
    sa.Column('randomized_prediction', sa.Integer(), nullable=True),
    sa.Column('gradient_prediction', sa.Integer(), nullable=True),
    sa.Column('final_defended_prediction', sa.Integer(), nullable=False),
    sa.Column('defense_agreement_score', sa.Float(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_analysis_logs_user_id'), 'anomaly_analysis_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_analysis_logs_user_id'), table_name='anomaly_analysis_logs')
    op.drop_table('anomaly_analysis_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('benchmark_results')
    # ### end Alembic commands ###
